seata:
  registry:
    #配置注册中心
      type: nacos
      nacos:
        server-addr: 127.0.0.1:8848
        application: seata-server   #配置服务名称
        username: nacos
        password: nacos
        group: SEATE-SERVER
  config:
    #配置中心读取一些数据
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      group: SEATE-SERVER
