server:
  port: 8081
spring:
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
  application:
    name: shop-skywalking
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?characterEncoding=utf-8&amp&serverTimezone=UTC&amp&useSSL=false
    password: 12345678
    username: root

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    #在启动里加上：-javaagent:E:\gitee\apache-skywalking-apm-8.6.0\apache-skywalking-apm-bin\agent\skywalking-agent.jar
    #-Dskywalking.agent.service_name=你的微服务名
    #-Dskywalking.collector.backend_service=127.0.0.1:11800

    #将它继承到每一个pom中
  #调用时候使用注解@Trace放到当前到业务方法上
  #添加另一个注解@Tages/@Tage  key表示返回值一般写方法名称列如：list/user  value记录参数 arg[0]/returnedObj

