server:
  port: 8081
spring:
  cloud:
    nacos:
      server-addr: localhost:8848
  application:
    name: product-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?characterEncoding=utf-8&amp&serverTimezone=UTC&amp&useSSL=false
    password: 12345678
    username: root

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect


